### PR TITLE
Fix interval being null in tail.stop() - closes #44

### LINKED ISSUE #44: remove interval doesn't work on file change

### PR DESCRIPTION
**Pull request by rowolff**
Fix interval being null on tail.stop() by using an instance of the object rather than calling the function.

### CODE REVIEW

File: src/components/electron/Filestream.js [hunk 1]
```diff
@@ -19,13 +19,20 @@ class Filestream extends React.Component {
...
     }
   }
 
   componentDidUpdate(prevProps) {
     if (prevProps.file !== this.props.file) {
-      tail(this.props.file[0]).start(
+      const Filetail = new Tail(this.props.file[0])
+      // because we use a conditon we can:
+      // eslint-disable-next-line react/no-did-update-set-state
+      this.setState({ prevFileInstance: Filetail })
```
Comment (vsetka) [inline src/components/electron/Filestream.js]: Shouldn't this `setState` happen *after* the conditional `prevFileInstance.stop()` below it?

File: src/utils/tail.js [hunk 2]
```diff
@@ -45,4 +45,4 @@ const tail = filePath => {
   }
 }
 
-module.exports = tail
+module.exports = Tail
```
Comment (vsetka) [inline src/utils/tail.js]: The name of the function is irrelevant as it gets exported directly. You could just do
```javascript
module.exports = filePath => {
  ...
}
```

File: src/components/electron/Filestream.js [hunk 3]
```diff
@@ -19,13 +19,20 @@ class Filestream extends React.Component {
...
       original: {},
-      intervalId: null
+      prevFileInstance: null
     }
   }
 
   componentDidUpdate(prevProps) {
     if (prevProps.file !== this.props.file) {
-      tail(this.props.file[0]).start(
+      const Filetail = new Tail(this.props.file[0])
```
Comment (vsetka) [inline src/components/electron/Filestream.js]: You don't need a `new` here. The util is just a function that returns an object and all the state it needs is in its closure (it doesn't rely on `this` for context).

Comment (rowolff) [reply src/components/electron/Filestream.js]: fixed in https://github.com/rowolff/babel-poe/commit/8d18bd30cf24aa5442c1e14cf46ec446c10b41b3

File: src/components/electron/Filestream.js (hunk 1 above)
Comment (rowolff) [reply src/components/electron/Filestream.js]: No - the set.state saves the current file in state, so if on a later file change (user selected a new file) the interval can be stopped on this.state.prevFileInstance. The order doesn't matter - but because it's confusing I did put it after the conditional and renamed `prevFileInstance` to `currentFileInstance` in https://github.com/rowolff/babel-poe/commit/8d18bd30cf24aa5442c1e14cf46ec446c10b41b3

File: src/utils/tail.js (hunk 2 above)
Comment (rowolff) [reply src/utils/tail.js]: thanks - changed in https://github.com/rowolff/babel-poe/commit/8d18bd30cf24aa5442c1e14cf46ec446c10b41b3
